from Variables.global_variables import *

OBSTACLES_NUMBER = 10
FRAME_SIZE = 20
FRAME_COLOR = (100, 100, 100)
NUMBER_OF_ENEMIES = 5
LEFT_UP_CORNER = (FRAME_SIZE, FRAME_SIZE)
RIGHT_UP_CORNER = (SCREEN_WIDTH - FRAME_SIZE, FRAME_SIZE)
LEFT_DOWN_CORNER = (FRAME_SIZE, SCREEN_HEIGHT - FRAME_SIZE)
RIGHT_DOWN_CORNER = (SCREEN_WIDTH - FRAME_SIZE, SCREEN_HEIGHT - FRAME_SIZE)

TOP_LINE = (LEFT_UP_CORNER, RIGHT_UP_CORNER)
DOWN_LINE = (LEFT_DOWN_CORNER, RIGHT_DOWN_CORNER)
RIGHT_LINE = (RIGHT_UP_CORNER, RIGHT_DOWN_CORNER)
LEFT_LINE = (LEFT_UP_CORNER, LEFT_DOWN_CORNER)