from Variables.global_variables import *

OBSTACLES_NUMBER = 15
FRAME_SIZE = 20
FRAME_COLOR = (100, 100, 100)
NUMBER_OF_ENEMIES = 15
OBSTACLE_MIN_RADIUS = 50
OBSTACLE_MAX_RADIUS = 60
LEFT_UP_CORNER = (FRAME_SIZE, FRAME_SIZE)
RIGHT_UP_CORNER = (SCREEN_WIDTH - FRAME_SIZE, FRAME_SIZE)
LEFT_BOTTOM_CORNER = (FRAME_SIZE, SCREEN_HEIGHT - FRAME_SIZE)
RIGHT_BOTTOM_CORNER = (SCREEN_WIDTH - FRAME_SIZE, SCREEN_HEIGHT - FRAME_SIZE)

TOP_BORDER = (LEFT_UP_CORNER, RIGHT_UP_CORNER)
BOTTOM_BORDER = (LEFT_BOTTOM_CORNER, RIGHT_BOTTOM_CORNER)
RIGHT_BORDER = (RIGHT_UP_CORNER, RIGHT_BOTTOM_CORNER)
LEFT_BORDER = (LEFT_UP_CORNER, LEFT_BOTTOM_CORNER)
